---
title: "raysahder"
author: "Geoffrey Arnold"
date: "1/18/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# installation
# devtools::install_github("tylermorganwall/rayshader")
require(raster)
require(rayshader)
require(rgdal)
require(elevatr)
require(rgl)

source("https://raw.githubusercontent.com/wcmbishop/rayshader-demo/master/R/map-image-api.R")

pitBounds <- readOGR("http://pghgis-pittsburghpa.opendata.arcgis.com/datasets/a99f25fffb7b41c8a4adf9ea676a3a0b_0.geojson") %>%
  spTransform(CRS("+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs"))

elv <- get_elev_raster(pitBounds, z =14)

elvCrop <- crop(elv, pitBounds@bbox)
pitElv <- mask(elvCrop, pitBounds)

pitM <- matrix(raster::extract(pitElv,raster::extent(pitElv), buffer=1000),
               nrow=ncol(pitElv),ncol=nrow(pitElv))

elvM <- matrix(raster::extract(elvCrop, raster::extent(elvCrop), buffer=1000),
               nrow=ncol(elvCrop),ncol=nrow(elvCrop))

rayElv <- ray_shade(elvM, lambert = TRUE)
ambElv <- ambient_shade(elvM)
waterMap <- detect_water(elvM)

bbox <- as.data.frame(pitBounds@bbox)

bbox <- list(
  p1 = list(long = bbox$min[1], lat = bbox$min[2]),
  p2 = list(long = bbox$max[1], lat = bbox$max[2])
)

overlay_file <- "images/basemap.png"
image <- get_arcgis_map_image(bbox, map_type = "World_Imagery", file = overlay_file, width = 5351, height = 4262)
overlay_img <- png::readPNG(overlay_file)
```

## Quick Map for testing textures

```{r}
elvM %>%
  sphere_shade(texture = "imhof4") %>%
  add_water(waterMap, color = "imhof4") %>%
  add_overlay(overlay_img, alphalayer = 0.5) %>%
  plot_map()
```

## Full Map

```{r map}
elvM %>%
  sphere_shade(texture = "imhof1") %>%
  add_water(waterMap, color= "imhof1") %>%
  add_shadow(rayElv, 0.7) %>%
  add_shadow(ambElv) %>%
  save_png("images/pittsburgh.png", rotate = 0)
```


## 3D Map Single

```{r}
zscale <- 10
rgl::clear3d()

elvM %>% 
  sphere_shade(texture = "imhof1") %>% 
  add_water(waterMap, color = "imhof1") %>%
  add_shadow(rayElv, max_darken = 0.5) %>%
  add_shadow(ambElv, max_darken = 0.5) %>%
  plot_3d(elvM, zscale = zscale, windowsize = c(1200, 1000),
          water = TRUE, soliddepth = -max(elvM)/zscale, wateralpha = 0,
          theta = 25, phi = 30, zoom = 0.65, fov = 60)

render_snapshot("images/3d_pittsburgh_imagery.png")

rgl::clear3d()
```

## 3D Gif

```{r}
source("https://raw.githubusercontent.com/wcmbishop/rayshader-demo/master/R/rayshader-gif.R")
n_frames <- 180
theta <- transition_values(from = 0, to = 360, steps = n_frames, 
                           one_way = TRUE, type = "lin")
phi <- transition_values(from = 10, to = 70, steps = n_frames, 
                         one_way = FALSE, type = "cos")
zoom <- transition_values(from = 0.4, to = 0.8, steps = n_frames, 
                         one_way = FALSE, type = "cos")

# GIF it!
zscale <- 10
elvM %>% 
  sphere_shade(texture = "imhof1") %>% 
  add_water(waterMap, color = "imhof1") %>%
  add_shadow(rayElv, 0.4) %>%
  add_shadow(ambElv, 0.4) %>%
  save_3d_gif(elvM, file = "images/pgh_3d.gif", duration = 6,
              zscale = zscale, windowsize = c(1200, 1000), wateralpha = 0,
              water = TRUE, soliddepth = -max(elvM)/zscale, 
              theta = theta, phi = phi, zoom = zoom, fov = 60)
```

